/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_oneday_videodemo_jni_JniInterface */

#ifndef _Included_com_oneday_videodemo_jni_JniInterface
#define _Included_com_oneday_videodemo_jni_JniInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_oneday_videodemo_jni_JniInterface
 * Method:    sayHelloToJniWorld
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_oneday_videodemo_jni_JniInterface_sayHelloToJniWorld
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
