/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_oneday_videodemo_jni_JniDemo */

#ifndef _Included_com_oneday_videodemo_jni_JniDemo
#define _Included_com_oneday_videodemo_jni_JniDemo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_oneday_videodemo_jni_JniDemo
 * Method:    sayHelloWorld
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_oneday_videodemo_jni_JniDemo_sayHelloWorld
  (JNIEnv *, jobject);

/*
 * Class:     com_oneday_videodemo_jni_JniDemo
 * Method:    printWord
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_oneday_videodemo_jni_JniDemo_printWord
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
