/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_oneday_videodemo_jni_JniDemo */

#ifndef _Included_com_oneday_videodemo_jni_JniDemo
#define _Included_com_oneday_videodemo_jni_JniDemo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_oneday_videodemo_jni_JniDemo
 * Method:    sayHelloWorld
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_oneday_videodemo_jni_JniDemo_sayHelloWorld
  (JNIEnv *, jobject);

/*
 * Class:     com_oneday_videodemo_jni_JniDemo
 * Method:    printWord
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_oneday_videodemo_jni_JniDemo_printWord
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_oneday_videodemo_jni_JniDemo
 * Method:    sumArray
 * Signature: ([I)I
 */
JNIEXPORT jint JNICALL Java_com_oneday_videodemo_jni_JniDemo_sumArray
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     com_oneday_videodemo_jni_JniDemo
 * Method:    create2DArray
 * Signature: (I)[[I
 */
JNIEXPORT jobjectArray JNICALL Java_com_oneday_videodemo_jni_JniDemo_create2DArray
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_oneday_videodemo_jni_JniDemo
 * Method:    accessField
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_oneday_videodemo_jni_JniDemo_accessField
  (JNIEnv *, jobject);

/*
 * Class:     com_oneday_videodemo_jni_JniDemo
 * Method:    accessMethod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_oneday_videodemo_jni_JniDemo_accessMethod
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
